[package]
name = "ragelab-studio"
version = "0.1.0"
description = "Desktop visual interface for RageLab"
authors = ["RageLab contributors"]
edition = "2021"
license = "Apache-2.0"
rust-version = "1.90"

[lib]
name = "ragelab_studio_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
ragelab-engine = { git = "https://github.com/RageLab/ragelab.git", rev = "e3be0f9973c1f14d8b6200d51648441fa557ca1f" }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
